service: lambda-grafanaexpressjohn

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 30
  stage: production
  region: ap-southeast-1

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /


    
      